{
  "hash": "838a1bb4038d15b843530f77bc0652d3",
  "result": {
    "engine": "knitr",
    "markdown": "---\nexamnum: \"Atividade 02\"\nstudent: \"Thiago Moraes Rizzieri\"\nclass: \"Aprendizado Supervisionado\"\nteacher: \"Prof. Dr. Ricardo Puziol de Oliveira\"\n\nlang: pt-br\n\nformat:\n  html:\n    theme: cosmo\n    toc: true\n    number-sections: true\n    embed-resources: true # Gera um arquivo único\n---\n\n\n\n**Disciplina:** Aprendizado Supervisionado Aplicado a Dados Biológicos e de Saúde\\\n**Professor:** Prof. Dr. Ricardo Puziol de Oliveira\\\n**Aluno:** Thiago Moraes Rizzieri\n\n## **Atividade Prática 2.1**\n\nConsidere o conjunto de dados `PimaIndiansDiabetes`, disponível na biblioteca `mlbench`, utilizado em estudos de saúde e epidemiologia para análise de fatores associados ao diabetes mellitus tipo 2. Esta base, em particular, contém informações clínicas e laboratoriais de mulheres adultas, incluindo variáveis numéricas relacionadas a medidas fisiológicas e um desfecho binário que indica a presença ou ausência de diabetes. Diante dessas características, e utilizando o ambiente R, responda aos itens a seguir referentes à primeira etapa da AED, correspondente à *visualização da estrutura e dos tipos de dados*.\n\n**(a)** Carregue o conjunto de dados `PimaIndiansDiabetes` e identifique:\n\n-   O número total de observações e de variáveis.\n\n-   Os nomes das variáveis e sua organização na base de dados.\n\n-   Indique quais funções do R são mais adequadas para essa inspeção estrutural inicial.\n\n**(b)** Examine os tipos de dados associados a cada variável (por exemplo, numérico, inteiro, fator). Com base nessa inspeção:\n\n-   Classifique as variáveis em contínuas, discretas e categóricas.\n\n-   Identifique o papel de cada variável no contexto de um estudo em saúde (por exemplo, variável resposta, covariável clínica ou fator de risco).\n\n**(c)** Verifique a presença de valores ausentes ou de valores que possam indicar codificações especiais (por exemplo, zeros em variáveis fisiológicas que não admitem esse valor).\n\n**(d)** Utilize funções de inspeção estrutural para:\n\n-   Obter um resumo geral da base.\n\n-   Identificar possíveis variáveis que necessitem de transformação de tipo (por exemplo, conversão de variável resposta para fator).\n\n-   Discuta por que essa etapa é fundamental antes da sumarização estatística ou da visualização gráfica propriamente dita.\n\n### **Solução**\n\n**(a)** Primeiramente, vamos carregar os dados:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(mlbench)\ndata(\"PimaIndiansDiabetes\")\ndados <- PimaIndiansDiabetes\nhead(dados)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  pregnant glucose pressure triceps insulin mass pedigree age diabetes\n1        6     148       72      35       0 33.6    0.627  50      pos\n2        1      85       66      29       0 26.6    0.351  31      neg\n3        8     183       64       0       0 23.3    0.672  32      pos\n4        1      89       66      23      94 28.1    0.167  21      neg\n5        0     137       40      35     168 43.1    2.288  33      pos\n6        5     116       74       0       0 25.6    0.201  30      neg\n```\n\n\n:::\n:::\n\n\nUma forma fácil de observar a estrutura das colunas contidas em um dataframe é utilizando a função `str()` do pacote base do R ou então a função `glimpse()` do dplyr.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAnexando pacote: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nOs seguintes objetos são mascarados por 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nOs seguintes objetos são mascarados por 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(dados, width = 60)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 768\nColumns: 9\n$ pregnant <dbl> 6, 1, 8, 1, 0, 5, 3, 10, 2, 8, 4, 10, 10,…\n$ glucose  <dbl> 148, 85, 183, 89, 137, 116, 78, 115, 197,…\n$ pressure <dbl> 72, 66, 64, 66, 40, 74, 50, 0, 70, 96, 92…\n$ triceps  <dbl> 35, 29, 0, 23, 35, 0, 32, 0, 45, 0, 0, 0,…\n$ insulin  <dbl> 0, 0, 0, 94, 168, 0, 88, 0, 543, 0, 0, 0,…\n$ mass     <dbl> 33.6, 26.6, 23.3, 28.1, 43.1, 25.6, 31.0,…\n$ pedigree <dbl> 0.627, 0.351, 0.672, 0.167, 2.288, 0.201,…\n$ age      <dbl> 50, 31, 32, 21, 33, 30, 26, 29, 53, 54, 3…\n$ diabetes <fct> pos, neg, pos, neg, pos, neg, pos, neg, p…\n```\n\n\n:::\n:::\n\n\nCom esse código, podemos observar que temos um total de 768 observações e 9 variáveis, sendo que `pregnant` é uma variável do tipo double (numérica), assim como as variáveis `glucose`, `pressure`, `triceps`, `insulin`, `mass`, `pedigree` e `age`. Além dessas, temos a variável `diabetes` que é do tipo fator.\n\n**(b)** Classifiquemos as variáveis:\n\n-   **pregnant**: variável numérica discreta. Representa uma covariável clínica.\n\n-   **glucose**: variável numérica discreta. Representa um fator de risco, pois na verdade os valores altos de glicose são o critério principal para o diagnóstico médico da diabetes.\n\n-   **pressure**: variável numérica discreta. Representa uma covariável clínica.\n\n-   **triceps**: variável numérica discreta. Representa uma covariável clínica.\n\n-   **insulin**: variável numérica discreta. Representa um fator de risco, pois como a insulina é o hormônio responsável por pegar a glicose no sangue e colocá-la dentro das células, essa variável acaba sendo praticamente um sintoma de que a pessoa possui diabetes.\n\n-   **mass**: variável numérica contínua. Representa um fator de risco, pois o excesso de gordura corporal pode causar resistência à insulina.\n\n-   **pedigree**: variável numérica contínua. Representa um fator de risco, pois, pelo que entendi, representa predisposição genética.\n\n-   **age**: variável numérica discreta. Representa uma covariável clínica.\n\n-   **diabetes**: variável categórica. Representa a variável resposta desta pesquisa, indicando se o teste da paciente foi positivo ou negativo em relação a diabetes.\n\n**(c)** Vamos usar a função `is.na()` para valores ausentes e verificar se há zeros em algumas variáveis.\n\nPrimeiramente em relação aos NAs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolSums(is.na(dados))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npregnant  glucose pressure  triceps  insulin     mass pedigree      age \n       0        0        0        0        0        0        0        0 \ndiabetes \n       0 \n```\n\n\n:::\n:::\n\n\nFelizmente estes dados aparentam não possuir nenhum valor ausente em nenhuma das variáveis. A princípio isso é uma notícia boa.\n\nMas vamos agora analisar se há valores zeros.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolSums(dados == 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npregnant  glucose pressure  triceps  insulin     mass pedigree      age \n     111        5       35      227      374       11        0        0 \ndiabetes \n       0 \n```\n\n\n:::\n:::\n\n\nApesar de não haver NAs nas nossas variáveis, existem muitos zeros em variáveis fisiológicas que não deveriam admitir esse valor. Isso inclui:\n\n-   glucose (5 zeros): Ninguém vivo tem zero de glicose no sangue (isso seria incompatível com a vida).\n\n-   pressure (35 zeros): Pressão arterial diastólica zero significa ausência de batimento cardíaco.\n\n-   triceps (227 zeros): É a espessura da dobra cutânea (gordura sob a pele). Por mais magra que a pessoa seja, é impossível a espessura ser exatamente zero milímetros.\n\n-   mass (11 zeros): É o Índice de Massa Corporal (IMC). Um IMC de zero significa que a pessoa não tem peso algum.\n\n-   insulin (374 zeros): Embora diabéticos tipo 1 possam ter níveis baixíssimos, no contexto deste exame laboratorial específico do banco de dados (insulina sérica de 2 horas), o zero foi usado pela equipe de coleta para indicar que o exame não foi realizado ou a amostra foi perdida. Observemos que quase metade do banco (374 de 768) tem esses \"zeros\".\n\nOu seja, isso significa que os zeros são na verdade NAs disfarçados.\n\n**(d)** Aplicando `dfSummary()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(summarytools)\ndfSummary(dados) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData Frame Summary  \ndados  \nDimensions: 768 x 9  \nDuplicates: 0  \n\n------------------------------------------------------------------------------------------------------------\nNo   Variable    Stats / Values             Freqs (% of Valid)    Graph                 Valid      Missing  \n---- ----------- -------------------------- --------------------- --------------------- ---------- ---------\n1    pregnant    Mean (sd) : 3.8 (3.4)      17 distinct values    :                     768        0        \n     [numeric]   min < med < max:                                 :                     (100.0%)   (0.0%)   \n                 0 < 3 < 17                                       :                                         \n                 IQR (CV) : 5 (0.9)                               : : .                                     \n                                                                  : : : : . .                               \n\n2    glucose     Mean (sd) : 120.9 (32)     136 distinct values             :           768        0        \n     [numeric]   min < med < max:                                         . : :         (100.0%)   (0.0%)   \n                 0 < 117 < 199                                            : : : .                           \n                 IQR (CV) : 41.2 (0.3)                                    : : : : .                         \n                                                                        : : : : : : :                       \n\n3    pressure    Mean (sd) : 69.1 (19.4)    47 distinct values              : .         768        0        \n     [numeric]   min < med < max:                                           : :         (100.0%)   (0.0%)   \n                 0 < 72 < 122                                               : :                             \n                 IQR (CV) : 18 (0.3)                                      : : : .                           \n                                                                  .       : : : : .                         \n\n4    triceps     Mean (sd) : 20.5 (16)      51 distinct values    :                     768        0        \n     [numeric]   min < med < max:                                 :   . :               (100.0%)   (0.0%)   \n                 0 < 23 < 99                                      : . : :                                   \n                 IQR (CV) : 32 (0.8)                              : : : : .                                 \n                                                                  : : : : :                                 \n\n5    insulin     Mean (sd) : 79.8 (115.2)   186 distinct values   :                     768        0        \n     [numeric]   min < med < max:                                 :                     (100.0%)   (0.0%)   \n                 0 < 30.5 < 846                                   :                                         \n                 IQR (CV) : 127.2 (1.4)                           : .                                       \n                                                                  : : .                                     \n\n6    mass        Mean (sd) : 32 (7.9)       248 distinct values           :             768        0        \n     [numeric]   min < med < max:                                         : :           (100.0%)   (0.0%)   \n                 0 < 32 < 67.1                                          : : :                               \n                 IQR (CV) : 9.3 (0.2)                                   : : : .                             \n                                                                      . : : : :                             \n\n7    pedigree    Mean (sd) : 0.5 (0.3)      517 distinct values   :                     768        0        \n     [numeric]   min < med < max:                                 :                     (100.0%)   (0.0%)   \n                 0.1 < 0.4 < 2.4                                  : :                                       \n                 IQR (CV) : 0.4 (0.7)                             : : :                                     \n                                                                  : : : : .                                 \n\n8    age         Mean (sd) : 33.2 (11.8)    52 distinct values    :                     768        0        \n     [numeric]   min < med < max:                                 :                     (100.0%)   (0.0%)   \n                 21 < 29 < 81                                     :                                         \n                 IQR (CV) : 17 (0.4)                              : : . .                                   \n                                                                  : : : : . . .                             \n\n9    diabetes    1. neg                     500 (65.1%)           IIIIIIIIIIIII         768        0        \n     [factor]    2. pos                     268 (34.9%)           IIIIII                (100.0%)   (0.0%)   \n------------------------------------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\nFelizmente a variável `diabetes` já aparece sendo do tipo fator, o que não é muito comum. Geralmente esse tipo de variável aparece sendo do tipo categórica e requer ser transformada para o tipo fator.\n\nPorém, a grande presença de zeros afeta significativamente as estatísticas descritivas, puxando as médias e medianas artificialmente para baixo.\n\nPodemos corrigir essa distorção substituindo os zeros incorretos pelo que de fato são, valores ausentes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados_corrigidos <- dados %>%\n  mutate(across(c(glucose, pressure, triceps, insulin, mass), ~na_if(., 0)))\n```\n:::\n\n\nAgora vejamos como isso afeta nas estatísticas descritivas dessas variáveis:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndfSummary(dados_corrigidos, \n          plain.ascii = FALSE,\n          graph.col = FALSE,   \n          valid.col = FALSE,   \n          headings = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n-----------------------------------------------------------------------------\nNo   Variable    Stats / Values               Freqs (% of Valid)    Missing  \n---- ----------- ---------------------------- --------------------- ---------\n1    pregnant\\   Mean (sd) : 3.8 (3.4)\\       17 distinct values    0\\       \n     [numeric]   min < med < max:\\                                  (0.0%)   \n                 0 < 3 < 17\\                                                 \n                 IQR (CV) : 5 (0.9)                                          \n\n2    glucose\\    Mean (sd) : 121.7 (30.5)\\    135 distinct values   5\\       \n     [numeric]   min < med < max:\\                                  (0.7%)   \n                 44 < 117 < 199\\                                             \n                 IQR (CV) : 42 (0.3)                                         \n\n3    pressure\\   Mean (sd) : 72.4 (12.4)\\     46 distinct values    35\\      \n     [numeric]   min < med < max:\\                                  (4.6%)   \n                 24 < 72 < 122\\                                              \n                 IQR (CV) : 16 (0.2)                                         \n\n4    triceps\\    Mean (sd) : 29.2 (10.5)\\     50 distinct values    227\\     \n     [numeric]   min < med < max:\\                                  (29.6%)  \n                 7 < 29 < 99\\                                                \n                 IQR (CV) : 14 (0.4)                                         \n\n5    insulin\\    Mean (sd) : 155.5 (118.8)\\   185 distinct values   374\\     \n     [numeric]   min < med < max:\\                                  (48.7%)  \n                 14 < 125 < 846\\                                             \n                 IQR (CV) : 113.8 (0.8)                                      \n\n6    mass\\       Mean (sd) : 32.5 (6.9)\\      247 distinct values   11\\      \n     [numeric]   min < med < max:\\                                  (1.4%)   \n                 18.2 < 32.3 < 67.1\\                                         \n                 IQR (CV) : 9.1 (0.2)                                        \n\n7    pedigree\\   Mean (sd) : 0.5 (0.3)\\       517 distinct values   0\\       \n     [numeric]   min < med < max:\\                                  (0.0%)   \n                 0.1 < 0.4 < 2.4\\                                            \n                 IQR (CV) : 0.4 (0.7)                                        \n\n8    age\\        Mean (sd) : 33.2 (11.8)\\     52 distinct values    0\\       \n     [numeric]   min < med < max:\\                                  (0.0%)   \n                 21 < 29 < 81\\                                               \n                 IQR (CV) : 17 (0.4)                                         \n\n9    diabetes\\   1\\. neg\\                     500 (65.1%)\\          0\\       \n     [factor]    2\\. pos                      268 (34.9%)           (0.0%)   \n-----------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\nAs estatísticas tiveram mudanças drásticas, desde os mínimo, as médias e os desvios-padrão de cada variável cometida à correção.\n\n## **Atividade Prática 2.2**\n\nConsidere o conjunto de dados **`NHANES`**, disponibilizado pela biblioteca `NHANES`, o qual deriva do *National Health and Nutrition Examination Survey*, um estudo observacional de base populacional conduzido de forma contínua nos Estados Unidos. Esse inquérito tem como objetivo central avaliar, de maneira integrada, o estado de saúde, o perfil nutricional e as condições socioeconômicas da população civil não institucionalizada. Para atender a esse propósito, a base de dados reúne informações provenientes de entrevistas domiciliares, exames clínicos padronizados e análises laboratoriais, o que resulta em um conjunto amplo e intrinsecamente heterogêneo de variáveis. Essas variáveis abrangem aspectos demográficos, antropométricos, clínicos, laboratoriais e comportamentais, incluindo tanto atributos numéricos contínuos — como idade, peso corporal, estatura, índice de massa corporal e diferentes biomarcadores — quanto variáveis discretas e categóricas, a exemplo de sexo, raça/etnia, nível educacional e estado civil, além de apresentar valores ausentes associados ao próprio desenho amostral e à aplicação de distintos módulos de coleta. Diante dessas características, e utilizando o ambiente R, responda aos itens a seguir referentes à segunda etapa da AED, correspondente à *sumarização dos dados*.\n\n**(a)** Selecione um subconjunto de *variáveis numéricas contínuas* do banco de dados `NHANES` (por exemplo, idade, peso, altura, índice de massa corporal ou medidas laboratoriais). Para cada uma dessas variáveis:\n\n-   Obtenha medidas de tendência central.\n\n-   Calcule medidas de dispersão apropriadas.\n\n-   Identifique valores mínimos, máximos e intervalos.\n\n-   Indique quais funções do R são mais adequadas para essa sumarização inicial.\n\n**(b)** Para as variáveis selecionadas em (a), utilize funções de posição relativa para:\n\n-   Calcular quartis e percentis selecionados das variáveis numéricas.\n\n-   Obter o intervalo interquartílico (IQR).\n\n-   Explicar como essas medidas contribuem para a compreensão da variabilidade e da assimetria dos dados em comparação às medidas baseadas na média e no desvio-padrão.\n\n**(c)** Selecione pelo menos *duas variáveis categóricas* (por exemplo, sexo, raça/etnia, escolaridade ou estado civil). Para essas variáveis:\n\n-   Construa tabelas de frequências absolutas.\n\n-   Obtenha as correspondentes frequências relativas.\n\n**(d)** Para as variáveis selecionadas em (c), investigue a presença de *valores ausentes*, isto é,\n\n-   Identifique quais variáveis apresentam maior proporção de dados faltantes.\n\n-   Calcule o percentual de valores ausentes por variável.\n\n**(e)** Utilizando funções do pacote `dplyr`, realize uma *sumarização estratificada*, considerando:\n\n-   Ao menos três variável numérica.\n\n-   Um fator de estratificação (por exemplo, sexo ou grupo etário).\n\n**(f)** Construa *tabelas de contingência* para investigar a associação descritiva entre variáveis categóricas selecionadas no conjunto `NHANES`. Para isso:\n\n-   Selecione duas variáveis categóricas (por exemplo, `Gender` × `Diabetes`, ou `Race1` × `Education`).\n\n-   Obtenha a tabela de frequências conjuntas por meio de `table()`.\n\n-   Calcule proporções por linha e por coluna utilizando `prop.table()` com o argumento `margin`.\n\n-   Interprete, em termos descritivos, as diferenças nas distribuições condicionais entre categorias, evitando conclusões inferenciais formais.\n\n-   Discuta em que situações tabelas de contingência são mais informativas do que frequências marginais e quais limitações devem ser consideradas quando há categorias com baixa frequência.\n\n**(g)** Utilize a função `mutate()` (biblioteca `dplyr`) para criar *variáveis* e apoiar a sumarização exploratória. Considere, por exemplo:\n\n-   A criação de faixas etárias (por exemplo, `AgeGroup`) a partir de `Age`, definindo pontos de corte clinicamente interpretáveis.\n\n-   A criação de uma variável indicadora (binária) para sobrepeso/obesidade a partir de `BMI`, segundo um critério previamente definido.\n\n-   A recodificação de variáveis categóricas (por exemplo, agregando níveis raros ou reordenando fatores) com o objetivo de tornar as sumarizações mais interpretáveis.\n\n**(h)** Empregue a biblioteca `summarytools` para produzir sumarizações *mais apresentáveis* das variáveis selecionadas nos itens anteriores. Em particular:\n\n-   Utilize `dfSummary()` para obter uma visão integrada do conjunto (tipos de variáveis, estatísticas descritivas, frequências e proporção de valores ausentes).\n\n-   Aplique `freq()` para sumarizar variáveis categóricas, reportando frequências absolutas e relativas, bem como percentuais cumulativos quando pertinente.\n\n-   Utilize `ctable()` para construir tabelas cruzadas (contingência) com apresentação ampliada, incluindo percentuais (por linha, por coluna ou totais), conforme apropriado.\n\n-   Discuta as vantagens do uso do `summarytools` em relatórios reprodutíveis (por exemplo, clareza, padronização e controle de apresentação) em comparação às funções base do R (`summary()`, `table()`, `prop.table()`), especialmente em bases heterogêneas como `NHANES`.\n\n### **Solução**\n\nAntes de tudo, vamos carregar estes dados:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(NHANES)\ndata(\"NHANES\")\ndados2 <- NHANES\nhead(dados2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 76\n     ID SurveyYr Gender   Age AgeDecade AgeMonths Race1 Race3 Education   \n  <int> <fct>    <fct>  <int> <fct>         <int> <fct> <fct> <fct>       \n1 51624 2009_10  male      34 \" 30-39\"        409 White <NA>  High School \n2 51624 2009_10  male      34 \" 30-39\"        409 White <NA>  High School \n3 51624 2009_10  male      34 \" 30-39\"        409 White <NA>  High School \n4 51625 2009_10  male       4 \" 0-9\"           49 Other <NA>  <NA>        \n5 51630 2009_10  female    49 \" 40-49\"        596 White <NA>  Some College\n6 51638 2009_10  male       9 \" 0-9\"          115 White <NA>  <NA>        \n# ℹ 67 more variables: MaritalStatus <fct>, HHIncome <fct>, HHIncomeMid <int>,\n#   Poverty <dbl>, HomeRooms <int>, HomeOwn <fct>, Work <fct>, Weight <dbl>,\n#   Length <dbl>, HeadCirc <dbl>, Height <dbl>, BMI <dbl>,\n#   BMICatUnder20yrs <fct>, BMI_WHO <fct>, Pulse <int>, BPSysAve <int>,\n#   BPDiaAve <int>, BPSys1 <int>, BPDia1 <int>, BPSys2 <int>, BPDia2 <int>,\n#   BPSys3 <int>, BPDia3 <int>, Testosterone <dbl>, DirectChol <dbl>,\n#   TotChol <dbl>, UrineVol1 <int>, UrineFlow1 <dbl>, UrineVol2 <int>, …\n```\n\n\n:::\n:::\n\n\n**(a)** Vamos selecionar algumas variáveis numéricas contínuas interessantes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados2_vars <- dados2 %>% \n  select(Age,Weight,Height,Poverty)\n```\n:::\n\n\nMedidas centrais:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados2_medias <- dados2_vars %>% \n  apply(.,2,mean,na.rm = TRUE)\n\ndados2_median <- dados2_vars %>% \n  apply(.,2,median,na.rm = TRUE)\n\nlibrary(DescTools)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: pacote 'DescTools' foi compilado no R versão 4.5.3\n```\n\n\n:::\n\n```{.r .cell-code}\ndados2_moda <- dados2_vars %>% \n  apply(.,2,Mode,na.rm = TRUE)\n\nkable(cbind(dados2_medias,dados2_median,dados2_moda), col.names = c(\"Médias\",\"Medianas\",\"Modas\"))\n```\n\n::: {.cell-output-display}\n\n\n|        |     Médias| Medianas| Modas|\n|:-------|----------:|--------:|-----:|\n|Age     |  36.742100|     36.0|  80.0|\n|Weight  |  70.981798|     72.7|  78.1|\n|Height  | 161.877838|    166.0| 173.2|\n|Poverty |   2.801844|      2.7|   5.0|\n\n\n:::\n:::\n\n\nMedidas de dispersão:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados2_var <- dados2_vars %>% \n  apply(.,2,var,na.rm = TRUE)\n\ndados2_sd <- dados2_vars %>% \n  apply(.,2,sd,na.rm = TRUE)\n\nep <- function(x, na.rm = FALSE){\n  if (na.rm) {\n    x <- na.omit(x)\n  }\n  sd(x) / sqrt(nrow(dados2))\n}\n\ndados2_ep <- dados2_vars %>% \n  apply(.,2,ep, na.rm = TRUE)\n\ndados2_IQR <- dados2_vars %>% \n  apply(.,2,IQR,na.rm = TRUE)\n\nkable(cbind(dados2_var,dados2_sd,dados2_ep,dados2_IQR), col.names = c(\"Variâncias\", \"Desvios-padrão\",\"Erros padrão\",\"IQRs\"))\n```\n\n::: {.cell-output-display}\n\n\n|        | Variâncias| Desvios-padrão| Erros padrão|  IQRs|\n|:-------|----------:|--------------:|------------:|-----:|\n|Age     | 501.650953|      22.397566|    0.2239757| 37.00|\n|Weight  | 848.286446|      29.125357|    0.2912536| 32.80|\n|Height  | 407.497471|      20.186567|    0.2018657| 17.70|\n|Poverty |   2.815379|       1.677909|    0.0167791|  3.47|\n\n\n:::\n:::\n\n\nFiz dessa forma, fazendo item por item para treinar, mas também podemos obter algumas estatísticas utilizando funções como `summary()` fornecendo um panorama geral instantâneo:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(dados2_vars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Age            Weight           Height         Poverty     \n Min.   : 0.00   Min.   :  2.80   Min.   : 83.6   Min.   :0.000  \n 1st Qu.:17.00   1st Qu.: 56.10   1st Qu.:156.8   1st Qu.:1.240  \n Median :36.00   Median : 72.70   Median :166.0   Median :2.700  \n Mean   :36.74   Mean   : 70.98   Mean   :161.9   Mean   :2.802  \n 3rd Qu.:54.00   3rd Qu.: 88.90   3rd Qu.:174.5   3rd Qu.:4.710  \n Max.   :80.00   Max.   :230.70   Max.   :200.4   Max.   :5.000  \n                 NA's   :78       NA's   :353     NA's   :726    \n```\n\n\n:::\n:::\n\n\n**(b)** Temos os quantis:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados2_quantile <- dados2_vars %>% \n  apply(.,2,quantile,probs = c(0.25,0.5,0.75),na.rm = TRUE)\ndados2_quantile\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Age Weight Height Poverty\n25%  17   56.1  156.8    1.24\n50%  36   72.7  166.0    2.70\n75%  54   88.9  174.5    4.71\n```\n\n\n:::\n:::\n\n\nE o IQR obtido no item anterior:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados2_IQR\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Age  Weight  Height Poverty \n  37.00   32.80   17.70    3.47 \n```\n\n\n:::\n:::\n\n\nO intervalo interquartílico também é uma medida de dispersão, mostrando a distância entre o primeiro e o terceiro quartil, em que ele mede a dispersão dos 50% centrais dos dados, ignorando valores anômalos (outliers). Também auxilia na visualização da assimetria dos dados, com o quanto cada quartil se distancia da mediana.\n\nAlém disso, diferentemente da média e do desvio-padrão, que são altamente sensíveis e puxados por valores extremos, a mediana e o IQR nos fornecem a representação mais realista do \\`\\`paciente comum\".\n\n**(c)** Vamos selecionar as variáveis: `Gender`, `Race1` e `Diabetes`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados2_cat <- dados2 %>% \n  select(Gender,Race1,Diabetes)\n```\n:::\n\n\nTemos a tabela de frequência absoluta dada por:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(dados2_cat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n, , Diabetes = No\n\n        Race1\nGender   Black Hispanic Mexican White Other\n  female   541      293     416  2973   369\n  male     512      262     509  2867   356\n\n, , Diabetes = Yes\n\n        Race1\nGender   Black Hispanic Mexican White Other\n  female    68       22      27   203    37\n  male      63       25      39   247    29\n```\n\n\n:::\n:::\n\n\nE de frequência relativa dada por:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.table(table(dados2_cat))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n, , Diabetes = No\n\n        Race1\nGender         Black    Hispanic     Mexican       White       Other\n  female 0.054879286 0.029722053 0.042199229 0.301582471 0.037431528\n  male   0.051937513 0.026577399 0.051633191 0.290829783 0.036112802\n\n, , Diabetes = Yes\n\n        Race1\nGender         Black    Hispanic     Mexican       White       Other\n  female 0.006897951 0.002231690 0.002738892 0.020592412 0.003753297\n  male   0.006390749 0.002536011 0.003956178 0.025055792 0.002941773\n```\n\n\n:::\n:::\n\n\n**(d)** Vamos analisar o percentual de NAs de cada variável categórica usada no item anterior:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nna_count <- colSums(is.na(dados2_cat))\nna_percent <- (na_count / nrow(dados2_cat)) * 100\n\nkable(cbind(`Valores Ausentes` = na_count, `Percentual (%)` = na_percent), digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|         | Valores Ausentes| Percentual (%)|\n|:--------|----------------:|--------------:|\n|Gender   |                0|           0.00|\n|Race1    |                0|           0.00|\n|Diabetes |              142|           1.42|\n\n\n:::\n:::\n\n\nConforme a tabela acima, a variável Diabetes apresenta a maior proporção de dados faltantes (1.42%), enquanto que as outras duas analisadas não possuem NAs.\n\n**(e)** Vou selecionar as variáveis numéricas correspondentes à idade, peso e altura, e a variável categórica sendo a etnia.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados2_grupo <- dados2 %>% \n  select(Age,Weight,Height,Race1)\n```\n:::\n\n\nVamos observar a média de cada variável numérica em cada etnia.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresumo <- dados2_grupo %>% \n  group_by(Race1) %>% \n  summarise(media_idade = mean(Age),\n            media_peso = mean(Weight,na.rm = TRUE),\n            media_altura = mean(Height,na.rm = TRUE))\nkable(resumo)\n```\n\n::: {.cell-output-display}\n\n\n|Race1    | media_idade| media_peso| media_altura|\n|:--------|-----------:|----------:|------------:|\n|Black    |    33.94486|   74.71797|     161.3279|\n|Hispanic |    31.72623|   65.72726|     156.2426|\n|Mexican  |    27.37635|   64.78868|     155.3785|\n|White    |    39.80273|   72.89313|     164.1409|\n|Other    |    32.29032|   62.12763|     157.0391|\n\n\n:::\n:::\n\n\n**(f)** Estarei utilizando a sugestão `Gender` × `Diabetes`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados2_cat <- dados2 %>% \n  select(Gender,Diabetes)\n```\n:::\n\n\nTemos a tabela de frequências conjuntas:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(dados2_cat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Diabetes\nGender     No  Yes\n  female 4592  357\n  male   4506  403\n```\n\n\n:::\n:::\n\n\nE as proporções utilizando o argumento `margin`$=1$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.table(table(dados2_cat), margin = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Diabetes\nGender           No        Yes\n  female 0.92786421 0.07213579\n  male   0.91790589 0.08209411\n```\n\n\n:::\n:::\n\n\nUtilizei a proporção por linha, dessa forma, podemos observar as distribuições condicionais da doença para cada gênero separadamente. Os dados indicam que, nesta amostra, a proporção de pacientes diagnosticados com diabetes é ligeiramente maior no sexo masculino (8.2%) em comparação ao feminino (7.2%).\n\n**(g)** Fiz as mudanças seguindo os seguintes critérios apresentados no próprio código:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados2 <- dados2 %>% \n  mutate(AgeGroup = ifelse(Age <= 18, \"Child\", ifelse(Age <= 65,\"Adult\",\"Elderly\")),\n         BMIclass = ifelse(BMI <= 18.5, \"Underweight\", ifelse(BMI <= 24.9,\"Healthy\", \"Overweight\")))\n```\n:::\n\n\n**(h)** Empregue a biblioteca `summarytools` para produzir sumarizações *mais apresentáveis* das variáveis selecionadas nos itens anteriores. Em particular:\n\n-   Utilize `dfSummary()` para obter uma visão integrada do conjunto (tipos de variáveis, estatísticas descritivas, frequências e proporção de valores ausentes).\n\n-   Aplique `freq()` para sumarizar variáveis categóricas, reportando frequências absolutas e relativas, bem como percentuais cumulativos quando pertinente.\n\n-   Utilize `ctable()` para construir tabelas cruzadas (contingência) com apresentação ampliada, incluindo percentuais (por linha, por coluna ou totais), conforme apropriado.\n\n-   Discuta as vantagens do uso do `summarytools` em relatórios reprodutíveis (por exemplo, clareza, padronização e controle de apresentação) em comparação às funções base do R (`summary()`, `table()`, `prop.table()`), especialmente em bases heterogêneas como `NHANES`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(dfSummary(dados2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData Frame Summary  \ndados2  \nDimensions: 10000 x 78  \nDuplicates: 2168  \n\n-----------------------------------------------------------------------------------------------------------------\nNo   Variable    Stats / Values                 Freqs (% of Valid)     Graph                 Valid      Missing  \n---- ----------- ------------------------------ ---------------------- --------------------- ---------- ---------\n1    ID          Mean (sd) : 61944.6 (5871.2)   6779 distinct values   . . . : . : . : : :   10000      0        \n     [integer]   min < med < max:                                      : : : : : : : : : :   (100.0%)   (0.0%)   \n                 51624 < 62159.5 < 71915                               : : : : : : : : : :                       \n                 IQR (CV) : 10134.5 (0.1)                              : : : : : : : : : :                       \n                                                                       : : : : : : : : : :                       \n\n2    SurveyYr    1. 2009_10                     5000 (50.0%)           IIIIIIIIII            10000      0        \n     [factor]    2. 2011_12                     5000 (50.0%)           IIIIIIIIII            (100.0%)   (0.0%)   \n\n3    Gender      1. female                      5020 (50.2%)           IIIIIIIIII            10000      0        \n     [factor]    2. male                        4980 (49.8%)           IIIIIIIII             (100.0%)   (0.0%)   \n\n4    Age         Mean (sd) : 36.7 (22.4)        81 distinct values     : .   . . . .         10000      0        \n     [integer]   min < med < max:                                      : : : : : : : .       (100.0%)   (0.0%)   \n                 0 < 36 < 80                                           : : : : : : : : . :                       \n                 IQR (CV) : 37 (0.6)                                   : : : : : : : : : :                       \n                                                                       : : : : : : : : : :                       \n\n5    AgeDecade   1. ·0-9                        1391 (14.4%)           II                    9667       333      \n     [factor]    2. ·10-19                      1374 (14.2%)           II                    (96.7%)    (3.3%)   \n                 3. ·20-29                      1356 (14.0%)           II                                        \n                 4. ·30-39                      1338 (13.8%)           II                                        \n                 5. ·40-49                      1398 (14.5%)           II                                        \n                 6. ·50-59                      1304 (13.5%)           II                                        \n                 7. ·60-69                       919 ( 9.5%)           I                                         \n                 8. ·70+                         587 ( 6.1%)           I                                         \n\n6    AgeMonths   Mean (sd) : 420.1 (259)        910 distinct values    :     .   .           4962       5038     \n     [integer]   min < med < max:                                      : : : : : : :         (49.6%)    (50.4%)  \n                 0 < 418 < 959                                         : : : : : : : : .                         \n                 IQR (CV) : 425 (0.6)                                  : : : : : : : : : .                       \n                                                                       : : : : : : : : : :                       \n-----------------------------------------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfreq(dados2_cat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFrequencies  \ndados2_cat$Gender  \nType: Factor  \n\n                Freq   % Valid   % Valid Cum.   % Total   % Total Cum.\n------------ ------- --------- -------------- --------- --------------\n      female    5020     50.20          50.20     50.20          50.20\n        male    4980     49.80         100.00     49.80         100.00\n        <NA>       0                               0.00         100.00\n       Total   10000    100.00         100.00    100.00         100.00\n\ndados2_cat$Diabetes  \nType: Factor  \n\n               Freq   % Valid   % Valid Cum.   % Total   % Total Cum.\n----------- ------- --------- -------------- --------- --------------\n         No    9098     92.29          92.29     90.98          90.98\n        Yes     760      7.71         100.00      7.60          98.58\n       <NA>     142                               1.42         100.00\n      Total   10000    100.00         100.00    100.00         100.00\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nctable(dados2_cat)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in parse_call(mc = match.call(), var = c(\"x\", \"y\"), var_label = FALSE,\n: metadata extraction terminated unexpectedly; inspect results carefully\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCross-Tabulation, Row Proportions  \nctable(x = dados2_cat) * structure(2L, levels = c(\"female\", \"male\", \"No\", \"Yes\"), class = \"factor\")  \n\n------------------------ ---------------------------------------------------------------------------- -------------- ------------ ------------ ----------------\n                           structure(2L, levels = c(\"female\", \"male\", \"No\", \"Yes\"), class = \"factor\")             No          Yes         <NA>            Total\n  ctable(x = dados2_cat)                                                                                                                                       \n                  female                                                                                4592 (91.5%)   357 (7.1%)    71 (1.4%)    5020 (100.0%)\n                    male                                                                                4506 (90.5%)   403 (8.1%)    71 (1.4%)    4980 (100.0%)\n                   Total                                                                                9098 (91.0%)   760 (7.6%)   142 (1.4%)   10000 (100.0%)\n------------------------ ---------------------------------------------------------------------------- -------------- ------------ ------------ ----------------\n```\n\n\n:::\n:::\n\n\nO uso do summarytools em relatórios reprodutíveis traz a vantagem de padronizar a apresentação visual e consolidar várias informações em uma única chamada. Em bases de dados grandes e heterogêneas como o NHANES, funções como dfSummary() calculam simultaneamente estatísticas descritivas, contagem de valores únicos e proporção de NAs, algo que exigiria dezenas de linhas de código usando apenas o R base.\n\n## **Atividade Prática 2.3**\n\nConsidere, novamente, o conjunto de dados **`NHANES`**, disponibilizado pela biblioteca `NHANES`, o qual deriva do *National Health and Nutrition Examination Survey*, um estudo observacional de base populacional conduzido de forma contínua nos Estados Unidos. As variáveis desta base abrangem aspectos demográficos, antropométricos, clínicos, laboratoriais e comportamentais, incluindo tanto atributos numéricos contínuos quanto variáveis discretas e categóricas, além de apresentar valores ausentes associados ao próprio desenho amostral e à aplicação de distintos módulos de coleta. Diante dessas características, e utilizando o ambiente R, responda aos itens a seguir referentes à terceira etapa da AED, correspondente à *visualização gráfica dos dados*.\n\n**(a) Histograma.**\n\n-   Selecione uma variável numérica contínua (por exemplo, `BMI` ou `TotChol`).\n\n-   Construa um histograma utilizando `hist()`.\n\n-   Refaça o histograma variando o argumento `breaks` (por exemplo, `\"Sturges\"` e `\"FD\"`).\n\n-   Discuta como a escolha do particionamento em classes influencia a percepção da forma da distribuição.\n\n**(b) Boxplot.**\n\n-   Construa um boxplot de uma variável numérica (por exemplo, `BMI`) estratificada por uma variável categórica (por exemplo, `Gender` ou `Diabetes`) utilizando `boxplot()`.\n\n-   Identifique, de forma descritiva, diferenças de posição (mediana), dispersão (IQR) e presença de valores extremos entre os grupos.\n\n**(c) Gráfico de Violino com `ggplot2`.**\n\n-   Reproduza a comparação do item (b) usando `ggplot()` e `geom_violin()`, inclua rótulos informativos com `labs()` e ajuste um tema com `theme()`.\n\n-   Discuta, em termos exploratórios, quais informações adicionais o gráfico de violino fornece em relação ao boxplot.\n\n**(d) Gráfico de Barras.**\n\n-   Selecione uma variável categórica (por exemplo, `Education` ou `Race1`).\n\n-   Construa um gráfico de barras com `barplot()` a partir de uma tabela de frequências (`table()`).\n\n-   Produza uma versão do gráfico em termos de frequências relativas e compare as interpretações obtidas.\n\n**(e) Tabela de Contingência.**\n\n-   Construa uma tabela de contingência entre duas variáveis categóricas (por exemplo, `Diabetes` × `Gender`, ou `SmokeNow` × `Education`) usando `table()`.\n\n-   Calcule proporções por linha e por coluna com `prop.table()`.\n\n-   Construa uma representação gráfica adequada para comparar as distribuições condicionais (por exemplo, barras lado a lado).\n\n**(f) Diagrama de Dispersão.**\n\n-   Selecione duas variáveis numéricas (por exemplo, `Weight` e `Height`, ou `BMI` e `TotChol`).\n\n-   Construa um gráfico de dispersão com `plot(x, y)`.\n\n-   Construa uma versão do gráfico de dispersão com `ggplot()` e `geom_point()`, discutindo possíveis padrões de associação, heterocedasticidade e presença de observações influentes.\n\n**(g) Matriz de Dispersão.**\n\n-   Selecione um subconjunto com pelo menos quatro variáveis numéricas contínuas (por exemplo, `Age`, `BMI`, `TotChol`, `BPSysAve`).\n\n-   Construa uma matriz de dispersão com `pairs()`.\n\n-   Identifique relações bivariadas que mereçam investigação adicional e discuta possíveis sinais de colinearidade.\n\n**(h) Visualização de Dados Ausentes.**\n\n-   Para as variáveis utilizadas nos itens anteriores, investigue e represente graficamente o padrão de valores ausentes (por exemplo, comparando a proporção de `NA` entre variáveis, ou estratificando por grupos).\n\n-   Discuta como a presença de dados faltantes pode afetar a interpretação dos gráficos produzidos.\n\n### **Solução**\n\n**(a)** Para o histograma utilizei a variável `BMI`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(dados2$BMI)\n```\n\n::: {.cell-output-display}\n![](Atividade02_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\nAgora com o argumento `breaks`=FD.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(dados2$BMI, breaks = 'FD')\n```\n\n::: {.cell-output-display}\n![](Atividade02_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\nA escolha do método de particionamento (breaks) altera a \"resolução\" da visualização. Ao utilizar o método \"FD\" (Freedman-Diaconis), o histograma fica com mais barras, revelando micro-padrões.\n\n**(b)**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nggplot(dados2, aes(x = Gender, y = BMI, fill = Gender))+\n  geom_boxplot()+\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 366 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Atividade02_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\nAs medianas de BMI entre os sexos masculino e feminino são muito próximas, ambas levemente acima de 25. O IQR também é semelhante, indicando variabilidade parecida nos 50% centrais. No entanto, o grupo feminino apresenta uma quantidade consideravelmente maior de valores extremos (outliers) na parte superior do gráfico, chegando a ultrapassar o valor 80 de BMI.\n\n**(c)**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dados2, aes(x = Gender, y = BMI, fill = Gender)) +\n  geom_violin(trim = FALSE) +\n  labs(title = \"Distribuição de BMI por Gênero\",\n       x = \"Gênero\",\n       y = \"Índice de Massa Corporal (BMI)\",\n       fill = \"Gênero\") +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 366 rows containing non-finite outside the scale range\n(`stat_ydensity()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Atividade02_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\nO gráfico de violino revela a densidade e o formato real da distribuição, além das informações obtidas com o boxplot.\n\n**(d)** Vou utilizar as etnias para realizar os gráficos.\n\nTemos o gráfico de barras para a frequência absoluta:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabela_race <- table(dados2$Race1)\nbarplot(tabela_race, main = \"Frequência Absoluta por Etnia\", col = \"steelblue\")\n```\n\n::: {.cell-output-display}\n![](Atividade02_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\nE o de frequência relativa:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabela_race_rel <- prop.table(tabela_race)\nbarplot(tabela_race_rel, main = \"Frequência Relativa por Etnia\", col = \"lightgreen\")\n```\n\n::: {.cell-output-display}\n![](Atividade02_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\nO formato dos dois gráficos é idêntico. A diferença fica na interpretação do eixo Y, sendo que a frequência absoluta nos mostra o volume real da amostra coletada, enquanto a frequência relativa nos permite entender a representatividade percentual de cada grupo.\n\n**(e)**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_contingencia <- table(dados2$Diabetes, dados2$Gender)\n\nbarplot(tab_contingencia, beside = TRUE, \n        col = c(\"lightcoral\", \"darkred\"),\n        legend = rownames(tab_contingencia),\n        main = \"Proporção de Diabetes por Gênero\",\n        xlab = \"Gênero\", ylab = \"Frequência\")\n```\n\n::: {.cell-output-display}\n![](Atividade02_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\nVisualmente é quase imperceptível a diferença da proporção de diabetes, mas vimos anteriormente que a proporção de diabetes entre os homens é singelamente superior.\n\n**(f)** Utilizando `plot()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(dados2$Height, dados2$Weight)\n```\n\n::: {.cell-output-display}\n![](Atividade02_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\nUtilizando `geom_point()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dados2, aes(x=Height, y=Weight))+\n  geom_point()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 366 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Atividade02_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\nO gráfico nos mostra uma associação linear positiva entre altura e peso. No entanto, podemos notar uma forte heterocedasticidade, em que visualmente temos uma nuvem de pontos em forma de \\`\\`cone\", ou seja, a variabilidade do peso é muito maior para pessoas altas do que para pessoas baixas. Há também observações influentes (outliers verticais) de indivíduos muito pesados para sua respectiva altura.\n\n**(g)**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados2_vars <- dados2 %>% \n  select(Age, BMI, TotChol, BPSysAve)\n\npairs(dados2_vars)\n```\n\n::: {.cell-output-display}\n![](Atividade02_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\nApesar de ser um gráfico bem poluído, podemos enxergar alguns padrões. Nota-se uma correlação positiva entre idade e BPSysAve, indicando que a pressão sistólica tende a subir ao longo de toda a vida. Além disso, aparenta existir uma correlação não-linear entre idade e BMI: observa-se um crescimento íngreme do BMI nas duas primeiras décadas de vida que se estabiliza em uma nuvem de alta dispersão na vida adulta.\n\n**(h)** Irei avaliar as variáveis numéricas:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontagem_na <- colSums(is.na(dados2_vars))\n\nbarplot(contagem_na, \n        main = \"Quantidade de Valores Ausentes por Variável Numérica\",\n        col = \"salmon\",\n        ylab = \"Número de NAs\",\n        xlab = \"Variáveis\",\n        las = 1) \n```\n\n::: {.cell-output-display}\n![](Atividade02_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\nA presença desses valores ausentes afeta diretamente a interpretação dos gráficos e as sumarizações anteriores. Precisaríamos ter feito essa análise antes de realizar as estatísticas das variáveis.\n",
    "supporting": [
      "Atividade02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}